### ISSUE TITLE
Make an ack/ag feature comparison chart

### ISSUE THREAD

**Issue by petdance** [beyondgrep/website#33]
I've been googling ack/ag/grep today, and it's frustrating that so many people say "ag is just like ack, but faster", when it's not "just like ack".  Yes, ag is typically much faster in execution speed, but that's only one aspect of the tools.  I'm thinking it would be handy to have a feature comparison chart on beyondgrep.com that puts the two biggest alternagreps side-by-side.

I want people to not just look at speed when comparing tools.  I want people to think about their use cases.  I want people to say "Oh, huh, I can do my own filetypes, I should look at ack", or "Oh, huh, I can search zip files, I should look at ag."  Ideally, people would say "Wow, they each do cool different things, I should look at both" but that might be too much to wish for....

**Comment by petdance** [comment]
ag does not support --sort-files. https://github.com/ggreer/the_silver_searcher/issues/107

**Comment by petdance** [comment]
ag searches zip files.

**Comment by n1vux** [comment]
Andy has addressed this this week, almost done.
The `comparison.json` file in dev branch has answered this ticket for *ack, ag, git, (gnu-)grep, rg* has the data, rendered by script `compare` script and TT and CSS. 

I will provide an update for `bsd|netbsd|freebsd|osx|posix` versions of `grep` (where Andy already re-marked Gnu grep as `gnu` on `dev` branch in preparation for this.)   How to render the other greps will be controlled by script `compare` enhancement TBD.  
(I'd suggest single column *grep* with the option text annotated by  letters `[BFGNOP]+` with a CSS class tag maybe "annotation-footnote";  CSS style for annotation-footnote is probably Superscript, size -1, fullcaps, contrasting color and/or face. And template needs to define those. )

**Notes**:

My source for *bsd and osx MAN pages was `https://www.unix.com/man-page/man` which has a long list of  OS distro variants of man pages.

Turns out that OSX is almost but not quite freebsd compatible. Dangerously almost.  

For future reference, to re-alphabetize the compound keys within `"ack,netbsd,gnu" : "something"` to  `"ack,gnu,netbsd" : "something"` as librarians and CDOs intended is
```
perl -i.bak -plE 'next unless /\w,\w/ and /\b(?:ack|ag|bsd|freebsd|git|gnu|netbsd|openbsd|posix|rg)\b/; s{(?<=")([a-z,]+)(?="\s*:\s*")}(join(q(,),sort split/,/,$1))e;' comparison.json 
```
(re-alphabetizing required since for common *bsd-isms, the easy VIM way is `:s/freebsd/freebsd,netbsd/` and then later `:s`. )

**Comment by petdance** [comment]
https://beyondgrep.com/feature-comparison/
